# Generated by Django 5.2.9 on 2025-12-02 19:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="Nombre")),
                ("last_name", models.CharField(max_length=30, verbose_name="Apellido")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos permitidos.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Telefono",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pictures/",
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "accepted_terms",
                    models.BooleanField(
                        default=False, verbose_name="Aceptó términos y condiciones"
                    ),
                ),
                (
                    "accepted_privacy",
                    models.BooleanField(
                        default=False, verbose_name="Aceptó política de privacidad"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, verbose_name="Email verificado"),
                ),
                (
                    "email_verification_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "password_reset_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "password_reset_token_created",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("google_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "facebook_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Canales de notificación preferidos",
                        verbose_name="Preferencias de notificación",
                    ),
                ),
                (
                    "appointment_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Recordatorios de turno"
                    ),
                ),
                ("points", models.IntegerField(default=0, verbose_name="Puntos")),
                (
                    "total_points_earned",
                    models.IntegerField(
                        default=0, verbose_name="Puntos totales ganados"
                    ),
                ),
                (
                    "total_points_redeemed",
                    models.IntegerField(
                        default=0, verbose_name="Puntos totales canjeados"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronce"),
                            ("silver", "Plata"),
                            ("gold", "Oro"),
                            ("platinum", "Platino"),
                        ],
                        default="bronze",
                        max_length=20,
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "total_appointments",
                    models.IntegerField(default=0, verbose_name="Total de turnos"),
                ),
                (
                    "completed_appointments",
                    models.IntegerField(default=0, verbose_name="Turnos completados"),
                ),
                (
                    "cancelled_appointments",
                    models.IntegerField(default=0, verbose_name="Turnos cancelados"),
                ),
                (
                    "no_show_count",
                    models.IntegerField(default=0, verbose_name="Inasistencias"),
                ),
                (
                    "current_streak",
                    models.IntegerField(default=0, verbose_name="Racha actual (meses)"),
                ),
                (
                    "longest_streak",
                    models.IntegerField(
                        default=0, verbose_name="Racha más larga (meses)"
                    ),
                ),
                (
                    "last_visit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Última visita"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "preferred_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_by_users",
                        to="core.branch",
                        verbose_name="Sucursal preferida",
                    ),
                ),
                (
                    "preferred_professional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_by_users",
                        to="core.professional",
                        verbose_name="Profesional preferido",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuarios",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Clave de sesión"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "device_info",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Información del dispositivo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Inicio de sesión"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actividad"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Usuario",
                "verbose_name_plural": "Sesiones de Usuarios",
                "ordering": ["-created_at"],
            },
        ),
    ]
