# Generated by Django 5.2.9 on 2025-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wants_promotions",
            field=models.BooleanField(
                default=False, verbose_name="Desea recibir promociones"
            ),
        ),
    ]
