# Generated by Django 5.2.9 on 2025-12-09 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("address", models.CharField(max_length=255, verbose_name="Dirección")),
                ("phone", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "opening_time",
                    models.TimeField(default="09:00", verbose_name="Hora de apertura"),
                ),
                (
                    "closing_time",
                    models.TimeField(default="19:00", verbose_name="Hora de cierre"),
                ),
                (
                    "monday_open",
                    models.BooleanField(default=True, verbose_name="Abierto lunes"),
                ),
                (
                    "tuesday_open",
                    models.BooleanField(default=True, verbose_name="Abierto martes"),
                ),
                (
                    "wednesday_open",
                    models.BooleanField(default=True, verbose_name="Abierto miércoles"),
                ),
                (
                    "thursday_open",
                    models.BooleanField(default=True, verbose_name="Abierto jueves"),
                ),
                (
                    "friday_open",
                    models.BooleanField(default=True, verbose_name="Abierto viernes"),
                ),
                (
                    "saturday_open",
                    models.BooleanField(default=True, verbose_name="Abierto sábado"),
                ),
                (
                    "sunday_open",
                    models.BooleanField(default=False, verbose_name="Abierto domingo"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Coordenada GPS para el mapa",
                        max_digits=9,
                        null=True,
                        verbose_name="Latitud",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Coordenada GPS para el mapa",
                        max_digits=9,
                        null=True,
                        verbose_name="Longitud",
                    ),
                ),
                (
                    "total_chairs",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad de sillas",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="branches/",
                        verbose_name="Imagen de la sucursal",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalUnavailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha inicio")),
                ("end_date", models.DateField(verbose_name="Fecha fin")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Dejar vacío para bloquear día completo",
                        null=True,
                        verbose_name="Hora inicio",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Dejar vacío para bloquear día completo",
                        null=True,
                        verbose_name="Hora fin",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacaciones"),
                            ("sick", "Enfermedad"),
                            ("personal", "Personal"),
                            ("training", "Capacitación"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Motivo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Indisponibilidad de Profesional",
                "verbose_name_plural": "Indisponibilidades de Profesionales",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(5)],
                        verbose_name="Duración (minutos)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Imagen del servicio",
                    ),
                ),
                (
                    "requires_deposit",
                    models.BooleanField(
                        default=False,
                        help_text="Si requiere pago de seña para reservar",
                        verbose_name="Requiere seña",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Monto de seña",
                    ),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Puntos que gana el cliente al completar este servicio",
                        verbose_name="Puntos que otorga",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellido"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biografía")),
                (
                    "specialties",
                    models.TextField(
                        blank=True,
                        help_text="Ej: Cortes modernos, Barba, Coloración",
                        verbose_name="Especialidades",
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Años de experiencia"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="professionals/",
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "monday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Lunes inicio"
                    ),
                ),
                (
                    "monday_end",
                    models.TimeField(blank=True, null=True, verbose_name="Lunes fin"),
                ),
                (
                    "tuesday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Martes inicio"
                    ),
                ),
                (
                    "tuesday_end",
                    models.TimeField(blank=True, null=True, verbose_name="Martes fin"),
                ),
                (
                    "wednesday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Miércoles inicio"
                    ),
                ),
                (
                    "wednesday_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Miércoles fin"
                    ),
                ),
                (
                    "thursday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Jueves inicio"
                    ),
                ),
                (
                    "thursday_end",
                    models.TimeField(blank=True, null=True, verbose_name="Jueves fin"),
                ),
                (
                    "friday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Viernes inicio"
                    ),
                ),
                (
                    "friday_end",
                    models.TimeField(blank=True, null=True, verbose_name="Viernes fin"),
                ),
                (
                    "saturday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Sábado inicio"
                    ),
                ),
                (
                    "saturday_end",
                    models.TimeField(blank=True, null=True, verbose_name="Sábado fin"),
                ),
                (
                    "sunday_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Domingo inicio"
                    ),
                ),
                (
                    "sunday_end",
                    models.TimeField(blank=True, null=True, verbose_name="Domingo fin"),
                ),
                (
                    "total_appointments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de turnos"
                    ),
                ),
                (
                    "completed_appointments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Turnos completados"
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Calificación promedio",
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de reseñas"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="professionals",
                        to="core.branch",
                        verbose_name="Sucursales donde trabaja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesional",
                "verbose_name_plural": "Profesionales",
                "ordering": ["first_name", "last_name"],
            },
        ),
    ]
