# Generated by Django 5.2.9 on 2025-12-09 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Usuario asociado (si tiene cuenta en el sistema)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professional_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="professionalunavailability",
            name="professional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unavailabilities",
                to="core.professional",
                verbose_name="Profesional",
            ),
        ),
        migrations.AddField(
            model_name="professional",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="professionals",
                to="core.service",
                verbose_name="Servicios que ofrece",
            ),
        ),
    ]
