# Generated by Django 5.2.9 on 2025-12-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professional",
            name="friday_end",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="friday_start",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="monday_end",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="monday_start",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="saturday_end",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="saturday_start",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="sunday_end",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="sunday_start",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="thursday_end",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="thursday_start",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="tuesday_end",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="tuesday_start",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="wednesday_end",
        ),
        migrations.RemoveField(
            model_name="professional",
            name="wednesday_start",
        ),
        migrations.CreateModel(
            name="ProfessionalSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        help_text="0=Lunes, 6=Domingo",
                        verbose_name="Día de la semana",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Hora de inicio")),
                ("end_time", models.TimeField(verbose_name="Hora de fin")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_schedules",
                        to="core.branch",
                        verbose_name="Sucursal",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="core.professional",
                        verbose_name="Profesional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de Profesional",
                "verbose_name_plural": "Horarios de Profesionales",
                "ordering": ["professional", "branch", "weekday"],
                "unique_together": {("professional", "branch", "weekday")},
            },
        ),
    ]
